### ISSUE TITLE
关于 refined storage 兼容

### ISSUE THREAD

**Issue by Towdium** [Towdium/JustEnoughCharacters#1]
讲道理我正在非常努力的尝试兼容refined storage，源码我也读的八九不离十了，但是悲伤的事情发生了：

我的dev环境下边根本不能正常载入refined storage! 疯狂的丢模型，以及在我根本没有调用的地方产生stacktrace，并不是很能解释这是个什么情况。

So any help on how to solve such problem?

**Comment by 3TUSK** [comment]
所以说AE2也有1.10.2了...

**Comment by Towdium** [comment]
@3TUSK 可以，这很火星。不知道有没有发布，不过我在github那边下下来稍微运行了一下，似乎没啥问题

**Comment by 3TUSK** [comment]
发布了
