### ISSUE TITLE
Compatibility with PSIonic Upgrades PSI升级的兼容性问题 

### ISSUE THREAD

**Issue by lyf666** [Towdium/JustEnoughCharacters#10]
很奇怪
JEC 1.12.0-1.10.0及1.12.0-2.0.0版本会使PSIU抛异常
PSI有个工作台来编辑术式，术式支持搜索功能，JEC 1.9.5版本时拼音搜索正常
估计新版本JEC的改动导致PSI工作台的class载入有问题？
log：[gist](https://gist.github.com/lyf666/92f779e66056398b2f667c7889f13112)

另外：我在之前使用JEC 1.9.4时，JEI搜索支持拼音、英文和高级信息内的搜索
例如：shuitong，bucket，water三个关键字都可搜出水桶
但现在不行了，不知道为什么（1.9.4和1.9.5）
也许是JEI或者其他什么的更新导致？
（mc版本：1.10.2，forge版本12.18.3.2422）

**Comment by Towdium** [comment]
已确认！正在修复

**Comment by Towdium** [comment]
应该已经修复了。具体原因是新版的 JECh 换用了新的 asm 接口，因为旧的接口已经被标记弃用了。不过目测新的 asm 库还没有普及，结果调不到新接口。

测试文件：
[JustEnoughCharacters-1.12.0-2.0.1.zip](https://github.com/Towdium/JustEnoughCharacters/files/1203151/JustEnoughCharacters-1.12.0-2.0.1.zip)

### edit:

关于 water 搜索的问题，这个就有点说来话长了。我解释一下这个是怎么出现的。

之前版本因为使用了暴力替换，导致会出现一些兼容性问题，其中有一个就是物品的 tooltip 会出现物品的注册名，也就是`minecraft:water_bucket`。尽管我不是很确定是和哪个mod的兼容性问题引起的，但是确实还挺常见，我怀疑是 Actually Additions，不过是谁并不重要。

然后 JEI 那边本身支持搜索 tooltip （在config里边有开关，默认打开的），这样结果就是物品的tooltip中的注册名被 JEI 搜索到了，变相的实现了搜索注册名，虽然本质上是一个 bug。

于是说新版本解决了这个 bug，tooltip 自然也就没有注册名出现了，自然也就搜索不到了。我这里提供两个解决方案：

- 如果你用的是 1.10 版本，使用 `F3+H` 开启 mc 原版的高级 tooltip，也就是将注册名添加到 tooltip 里了。然后重启 mc，应该就能搜索注册名了；
- 如果你用的是 1.11 以上， JEI 自带搜索注册名的功能，在 config 中设置`S:resourceIdSearchMode=DISABLED` 为 `require_prefix`（需要前缀&） 或者 `enabled`（默认开启），就可以直接搜索注册名。

**Comment by lyf666** [comment]
收到，晚上测试下

**Comment by lyf666** [comment]
不冲突了，但是高级tooltip我一直有开，还是没办法中英混合搜索

**Comment by Towdium** [comment]
我这里测试的话高级 tooltip 打开之后就可以搜索英文了啊....
你的 JEI 可以搜索其他 mod 的 tooltip 嘛？

发张图：
![screenshot from 2017-08-09 00-26-16](https://user-images.githubusercontent.com/10866568/29082853-7b0083ca-7c99-11e7-9f3e-809a92219099.png)
