### ISSUE TITLE
很奇怪的问题，jec 1.16.5最新版本在Chroma Endless无法在jei和创造物品栏直接搜索，再其他mod上却可以

### ISSUE THREAD

**Issue by baka4n** [Towdium/JustEnoughCharacters#101]
![image](https://github.com/Towdium/JustEnoughCharacters/assets/60695447/53acc485-e867-454c-b157-0e1615b1b1cc)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/60695447/60ac408c-2196-4657-b397-1a3d2f89a836)

**Comment by vfyjxf** [comment]
在新版本已修复
