### ISSUE TITLE
1.19 【资源蜜蜂】Productive Bees不兼容

### ISSUE THREAD

**Issue by Duoq233** [Towdium/JustEnoughCharacters#106]
用中文能搜索到蜜蜂，但用拼音搜索却搜不到
![石英蜜蜂](https://github.com/Towdium/JustEnoughCharacters/assets/89086794/ec888cee-b09f-43f7-bd32-ca4e3e18ac2f)
![全拼](https://github.com/Towdium/JustEnoughCharacters/assets/89086794/7c6633a7-df42-4a1b-aa90-498fea00dccd)

**Comment by vfyjxf** [comment]
已修复
