### ISSUE TITLE
1.20.1 forge版本无法使用双拼

### ISSUE THREAD

**Issue by Forever-178** [Towdium/JustEnoughCharacters#110]
游戏版本: 1.20.1
Forge版本: 47.2.0
mod列表: 只有jec ( 测试过4.4.1，4.5.0，4.5.2三个版本 )

配置文件中，enumKeyboard值已经设置为了"ZIRANMA"
尝试在创造模式物品栏中搜索，其中4.4.1版本可以正常使用双拼搜索，4.5.0与4.5.2只能使用全拼

以“橡木”（自然码输入方案 按键序列为 "xdmu") 为例: 
在4.5.0与4.5.2版本中，"xdmu"结果为空，"xiangmu"可得到正确结果
在4.4.1版本中，"xdmu"得到正常结果，"xiangmu"结果为空

**Comment by vfyjxf** [comment]
已修复，更新还要等一段时间才发布。
