### ISSUE TITLE
4.5.x存在的BUG

### ISSUE THREAD

**Issue by Duoq233** [Towdium/JustEnoughCharacters#112]
Minecraft版本：1.19.2
Forge版本：43.2.14
jech版本：4.5.3
使用/jech keyboard 指令切换输入法后重启游戏，需要重新输入指令

以下模组不兼容
IntegratedTerminals版本：1.4.10
RFToolsStorage版本：4.1.2

**Comment by vfyjxf** [comment]
这周没什么时间，先把配置文件的问题修了，兼容之后再修。

**Comment by vfyjxf** [comment]
已修复，请查看更新

**Comment by Duoq233** [comment]
> 已修复，请查看更新

Minecraft版本：1.20.1
Forge版本：47.2.19
jech版本：4.5.5

以下模组仍然不兼容
IntegratedTerminals版本：1.4.12
RFToolsStorage版本：1.20-5.0.2
