### ISSUE TITLE
1.16.5 Crash | Forge 36.2.41

### ISSUE THREAD

**Issue by MuCloudOfficial** [Towdium/JustEnoughCharacters#113]
[crash-2024-01-25_19.09.02-client.txt](https://github.com/Towdium/JustEnoughCharacters/files/14050790/crash-2024-01-25_19.09.02-client.txt)

使用 JECH 4.5.6 时启动产生了 ___java.lang.NoClassDefFoundError___ 和 ___java.lang.ClassNotFoundException: me.towdium.jecharacters.utils.FakeArray___  

Occured Exceptions:  ___java.lang.NoClassDefFoundError___ and ___java.lang.ClassNotFoundException: me.towdium.jecharacters.utils.FakeArray___ by using JECH MOD 4.5.6

**Comment by vfyjxf** [comment]
请检查是否是别的mod原因，在只有jech和jei存在的时候并不会有这个问题。

**Comment by vfyjxf** [comment]
能否提供一个整合包，在加了jech就会出现上述问题的呢？

**Comment by vfyjxf** [comment]
我推测可能不是jech本身造成的问题，可能是某些优化mod造成的bug。

**Comment by MuCloudOfficial** [comment]
已经组了一个新的整合，原环境已不可考。

**Comment by LFJiHan** [comment]
与[玉米乐事 corn_delight-1.0.3-1.16.5.jar](https://www.mcmod.cn/class/5646.html)一同加载时会出现以上错误
[Uploading crash-2024-06-09_16.46.02-client.txt…]()
