### ISSUE TITLE
1.16.5Forge版本的报错

### ISSUE THREAD

**Issue by QilinXioahui** [Towdium/JustEnoughCharacters#118]
![屏幕截图 2024-02-08 105136](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/2c104409-1e69-4399-9e14-62c6b5e94e24)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/434c8ee3-67a9-4535-8fb7-e50f5e1f9f65)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/7b1f1275-004f-40d2-8d5c-6eebdf4e45b6)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/9d16b35c-3b17-44b8-b041-f7d2f295dee8)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/d89c50df-9419-4f83-8bc0-1cd792492a98)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/66ee6cca-001f-4209-b966-9fc8277be275)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/ed308bbf-725e-4de8-b04e-a7618d4a940b)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/da8c14dd-160f-4739-a55a-c7f59eed9b59)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/159400543/a6dd2726-3abe-4f30-a915-8d432aa15eab)
[错误报告-2024-2-8_10.59.41.zip](https://github.com/Towdium/JustEnoughCharacters/files/14203769/-2024-2-8_10.59.41.zip)
forge版本：36.2.39
使用java：jre8（8.0.391）（jjdk11.0.6也试过了）

**Comment by vfyjxf** [comment]
请试试删除jech，看看是否还会崩溃，这可能不是jech的问题。

**Comment by vfyjxf** [comment]
在只有jech和jei的情况下，是不会出现这种问题的。

**Comment by vfyjxf** [comment]
![image](https://github.com/Towdium/JustEnoughCharacters/assets/42764413/0d435b87-807c-44f0-9b19-71d83e843145)
见上图

**Comment by ZekerZhayard** [comment]
[铷] rubidium-mc1.16.5-0.2.13.jar 模组和 embeddium-0.3.0+mc1.16.5.jar 模组 两个只能装一个

**Comment by MuCloudOfficial** [comment]
并不只是因为这个，我刚才去curseforge上找了之前组的包，也有这个问题

**Comment by vfyjxf** [comment]
> 并不只是因为这个，我刚才去curseforge上找了之前组的包，也有这个问题

原因不会是jech的问题（大部分情况下），jech只是因为forge的某些原因背锅了（）

**Comment by MuCloudOfficial** [comment]
我刚才试了一下，可以尝试在清渲染模组（Rubiddum和Embeddium任选其一及其附属）的同时尝试删除包内 MemoryLeakFix 模组

**Comment by MuCloudOfficial** [comment]
这个组的包确实一眼看有很多问题((((((
