### ISSUE TITLE
【1.12.2】JEI更新，导致JEC不工作

### ISSUE THREAD

**Issue by huangsijun17** [Towdium/JustEnoughCharacters#123]
1.12.2的JEI似乎改了一系列代码，改用maven打包了，导致现有的JEC不工作。

**Comment by vfyjxf** [comment]
看了下jei的更改，貌似没有更改搜索部分的代码，你是不是用的HEI，hei的兼容要加hech

**Comment by huangsijun17** [comment]
> 看了下jei的更改，貌似没有更改搜索部分的代码，你是不是用的HEI，hei的兼容要加hech

谢谢，整合包确实是HEI。
