### ISSUE TITLE
1.20.1版本不支持最新版AE

### ISSUE THREAD

**Issue by Xiaoshan1587** [Towdium/JustEnoughCharacters#126]
![2024-06-21_20 07 43](https://github.com/Towdium/JustEnoughCharacters/assets/142152230/0859a826-b309-462a-8406-160c5b939550)
![2024-06-21_20 07 51](https://github.com/Towdium/JustEnoughCharacters/assets/142152230/dad8ddc7-42af-4013-9b6f-47499c44c728)
1.20.1本模组无法支持最新版AE的终端搜索，但1.20.1老版本正常支持

**Comment by vfyjxf** [comment]
已经修复
