### ISSUE TITLE
1.21Fabric版本 搜索失效

### ISSUE THREAD

**Issue by Spturate** [Towdium/JustEnoughCharacters#128]
如题 搜索失效，Fabric加载器和API都是最新的版本
[latest.log](https://github.com/user-attachments/files/16068928/latest.log)
![QQ截图20240702212427](https://github.com/Towdium/JustEnoughCharacters/assets/30800649/647e23fa-ecb6-4b5f-84a3-bde416e5332f)

**Comment by vfyjxf** [comment]
原版兼容好像很久就坏了，但一直没人反馈我就忘了（

**Comment by vfyjxf** [comment]
修了
