### ISSUE TITLE
Crash when not connected to Internet 离线启动时崩溃

### ISSUE THREAD

**Issue by Towdium** [Towdium/JustEnoughCharacters#13]
由 @bakafn 提出，转移到这个 issue
正常启动时的日志： https://paste.ubuntu.com/26352393/
断网时崩溃的日志：https://paste.ubuntu.com/26352398/

**Comment by Towdium** [comment]
@bakafn 可以问一下你使用的mod版本么？按理说昨天的更新（2.2.2）应该已经修复了这个问题。
如果确定是新版的话，可否描述一下你使用的整合和复现经过？
我这里在1.12.2最新forge环境下断网启动也没有成功重现类似的崩溃

**Comment by bakafn** [comment]
感谢修复，上次用的是2.2.0

**Comment by Towdium** [comment]
@bakafn 新版确定修复崩溃了嘛？没问题的话我就关闭issue了

**Comment by bakafn** [comment]
en，我测试了20次了
话说为什么不依赖JEI啊

**Comment by Towdium** [comment]
emmmm 这个有点说来话长
这个mod最早写出来的时候是JEI限定的，那时候JEI确实算作了依赖
到后来又支持了很多其他的mod，就是你在 #3 里边能看到的那些，除去原版还有23个mod
对于这些mod，如果你安装了的话，都会自动兼容，但是没有安装的话也不会有任何影响
现在JEI的兼容和所有mod的兼容是一样的，没有JEI的情况下它也会正常兼容其他mod
严格而言这23个mod都可以算作是可选依赖，不过这么填的话依赖列表一大串，看上去就让人血压升高
所以就干脆不填了，不过某一天我可能又会想把它们全部列出来 XD
