### ISSUE TITLE
jei可以用拼音搜索，但是rei不行 麻烦适配？两边我都说了看你们吧

### ISSUE THREAD

**Issue by wearfaa** [Towdium/JustEnoughCharacters#131]
如题 jei没rei好用 但是rei没有办法进行拼音搜索

**Comment by vfyjxf** [comment]
rei自带rei物品列表的拼音搜索，如果你需要在rei使用jech的拼音搜索算法，请看https://github.com/vfyjxf/Jech-Rei-Compatibility

**Comment by h15588** [comment]
rei自带拼音搜索，只是得手动开启
