### ISSUE TITLE
fabric1.20.1不能用拼音搜索最新版ae里的东西

### ISSUE THREAD

**Issue by snpdzk** [Towdium/JustEnoughCharacters#133]
![image](https://github.com/user-attachments/assets/9112349c-2397-4b80-a5be-6c5ee073db69)
![image](https://github.com/user-attachments/assets/8b97a3c0-6d4d-4155-a194-b0bc38aca1a6)

**Comment by vfyjxf** [comment]
试试curseforge上面的最新版，modr上面的不是最新的应该

**Comment by snpdzk** [comment]
![image](https://github.com/user-attachments/assets/8bc0e378-7e03-4818-bf40-c708a3eea3e2)
![image](https://github.com/user-attachments/assets/a3170cff-821a-48e7-8eab-b105e1f65d6a)
![image](https://github.com/user-attachments/assets/5f27f901-997a-4193-a342-f5f54d61fcfd)

cf上最新版也不行

**Comment by AshdoII** [comment]
有同样的问题，ae版本15.2.12，jech版本4.5.6

**Comment by Yang00002** [comment]
这个问题应该和 [issue 134](https://github.com/Towdium/JustEnoughCharacters/issues/134) 是同样的原因, 可以通过改文件解决.

把 jecharacters-1.20.1-fabric-4.5.6.jar 解压后 将
jecharacters-1.20.1-fabric-4.5.6\me\towdium\jecharacters\targets.json 替换成下面这个 [targets.json](https://github.com/user-attachments/files/17349075/targets.json)

这个文件是从 multiple-version 分支构建得到的. 这个分支应该修复了 ae2 15.2.12 的的支持问题, 但不知道为什么没发布新版本.

**Comment by vfyjxf** [comment]
🌿，还有这回事，我看看为啥没传

**Comment by AshdoII** [comment]
替换完targets.json之后能正常搜索了，谢谢。

**Comment by YuriMontana** [comment]
15.2.13同样方法覆盖进4.5.10版本的jech以后还是不行

**Comment by vfyjxf** [comment]
上传了支持的jech
