### ISSUE TITLE
AE2 15.2.11 JEC拼音搜索失效

### ISSUE THREAD

**Issue by chouzz** [Towdium/JustEnoughCharacters#134]
如下面动态图所示，在AE2中搜索shitou无结果，在JEI中搜索shitou能得到结果
![javaw_6Fn3rXNf8v](https://github.com/user-attachments/assets/3e7fad91-c982-48f7-8006-277e6253411b)

版本如下：
![javaw_slUlGoBcUM](https://github.com/user-attachments/assets/baa8b06c-6991-433c-801b-90eda351bbc4)

**Comment by chouzz** [comment]
好像是因为AE2的这个[PR](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/5105)从12.9.2中将interfaceterminal重命名为patternaccess了，看了下，应该需要在python脚本的`contains`里面增加：

```
'appeng.client.gui.me.patternaccess.PatternAccessTermScreen:itemStackMatchesSearchTerm(Lnet/minecraft/world/item/ItemStack;Ljava/lang/String;)Z', # Applied Energistics 2 since 12.9.2
'appeng.client.gui.me.patternaccess.PatternAccessTermScreen:refreshList()V', # Applied Energistics 2 since 12.9.2
```
但是只增加这个可能还不行，好像还需要修改`regExp`部分，这部分就不知道咋修改了。

@Towdium 能指导下如何修改或者修复下这个问题吗？

**Comment by chouzz** [comment]
好像已经改了，得下载neoforge的Jech版本，怪不得检查更新一直显示Jech 4.5.4已经最新版本。

https://modrinth.com/mod/justenoughcharacters/versions

**Comment by vfyjxf** [comment]
试试curseforge上面的最新版，modr上面的不是最新的

**Comment by chouzz** [comment]
好的，那应该就是modrinth没更新导致的，我用的prisim launcher，默认mod更新源modrinth
