### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by Tmwhmk** [Towdium/JustEnoughCharacters#14]
![xxl](https://user-images.githubusercontent.com/13309497/38779070-e2c60068-40f5-11e8-9c99-79c80de36a6e.jpg)
release2.2.2会导致jei的物品列表显示不全
挺有意思的bug

**Comment by Towdium** [comment]
请问你的 forge，JEI, NEI 版本是？

**Comment by Tmwhmk** [comment]
forge：12.18.3.2254
jei_1.10.2-3.14.7.416
NotEnoughItems-1.10.2-2.1.3.201-universal
另外我用的是FTB的FTB Sky Factory Challenges整合包

**Comment by Towdium** [comment]
我这儿 Sky Factory Challenges 完全正常啊.....

![2018-05-01_15 02 14](https://user-images.githubusercontent.com/10866568/39475589-b01fcdf8-4d50-11e8-9286-aec340bdc54c.png)

**Comment by Towdium** [comment]
问题依然存在么？
重新下载整合包/重新安装仍然不能解决么？
