### ISSUE TITLE
Player ran into a crash with this mod

### ISSUE THREAD

**Issue by Sunconure11** [Towdium/JustEnoughCharacters#20]
https://paste.dimdev.org/iyabiwibig.mccrash

**Comment by Towdium** [comment]
Thanks for report！ Will look into it soon

**Comment by Sunconure11** [comment]
https://paste.dimdev.org/kikowacora.mccrash

**Comment by Towdium** [comment]
I have changed some code very possibly causing this issue in ca3868785076118917d54b5dcefe7880f66d34ab. I'm closing this issue, but feel free to leave more comments.
