### ISSUE TITLE
搜索 “hsz” 不能检索到红石中继器

### ISSUE THREAD

**Issue by Zhang-Wei-666** [Towdium/JustEnoughCharacters#21]
图:
[搜索: "hsz" 无效](http://github.zw-blog.com/2018-10-28_20-56-52.png)
[搜索: "hongshizhongjiqi" 有效](http://github.zw-blog.com/2018-10-28_20-58-8.png)

Mod 版本: JustEnoughCharacters-1.12.0-3.1.1
游戏版本: 1.12.2
配置: 默认配置

**Comment by Towdium** [comment]
请在配置文件中打开z=zh,s=sh,c=ch模糊音,或者搜索hshzh

**Comment by Zhang-Wei-666** [comment]
@Towdium  已解决, 谢谢 ~
