### ISSUE TITLE
多音字不能正常识别

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [Towdium/JustEnoughCharacters#22]
在jei搜索“音乐唱片”时，输入“yinyuechangpian”不显示，只能输入“yinlechangpian”。

**Comment by Towdium** [comment]
多谢反馈！
这个问题我已知很久了，原因是新版本中使用的词典缺少一些音。不过我最近太忙没时间修，建议你退回到2.3.2版本，多半可以解决问题。
