### ISSUE TITLE
Config GUI i18n

### ISSUE THREAD

**Issue by bakaxyf** [Towdium/JustEnoughCharacters#28]
看其他mod cfg是有i18n的 [比如forge](https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/resources/assets/forge/lang/en_US.lang#L12-L57)
加一个能帮助用户使用？
![image](https://user-images.githubusercontent.com/10368307/74106029-0cce8b00-4b9e-11ea-906e-d8e8a356e370.png)

**Comment by Towdium** [comment]
1.14 以上版本配置大改，config gui 都没了。按目前 1.12 的情况不打算做了，1.14看情况也许会有。
