### ISSUE TITLE
请考虑支持一下1.7.10

### ISSUE THREAD

**Issue by InTheManXG** [Towdium/JustEnoughCharacters#30]
非常感谢，一直都挺依赖这样的mod，很方便很实用，不用一直来回切换输入法。原来的1.7.10的mod，因为nei更新，已经无法使用了，联系不到作者，所以希望这个mod能支持1.7.10。非常感谢。

**Comment by Towdium** [comment]
1.7.10 参见 [MoeNetwork/NotEnoughCharacters](https://github.com/MoeNetwork/NotEnoughCharacters)
