### ISSUE TITLE
[Enhancement] Bump version range to work with 1.16.1

### ISSUE THREAD

**Issue by yezhiyi9670** [Towdium/JustEnoughCharacters#31]
Forge 1.16.1 is out. As a small mod, JECh should add support for it.

Note: According to my researches, the only thing you need to do is to bump version range. The 1.15.2 jar file works fine with 1.16.1.

**Comment by yzl210** [comment]
Also need to update message sending, it will crash. I created a PR #32

**Comment by Towdium** [comment]
Updated, thanks to @yzl210
