### ISSUE TITLE
[Question]目前拼音引擎仅将ü识别成u

### ISSUE THREAD

**Issue by iMusynx** [Towdium/JustEnoughCharacters#37]
RT,is it a feature?

**Comment by Towdium** [comment]
``绿: lv4, lu4``

确定不是因为"绿"是多音字？

![图片](https://user-images.githubusercontent.com/10866568/101272755-30685f00-37ca-11eb-9704-0d7342542d25.png)

有什么问题嘛？？？

**Comment by iMusynx** [comment]
好像是我脑抽（

**Comment by iMusynx** [comment]
> 
> 
> `绿: lv4, lu4`
> 
> 确定不是因为"绿"是多音字？
> 
> ![图片](https://user-images.githubusercontent.com/10866568/101272755-30685f00-37ca-11eb-9704-0d7342542d25.png)
> 
> 有什么问题嘛？？？

数据 据: jv4,好像确实是这个问题(
只能搜ju不能搜jv,虽然没有ju这个读音(

**Comment by Towdium** [comment]
> 由于拼音尽量减省字母尽量达成能够只用一个字母分别表示声母、韵母、介音的效果，同一拼音字母出现在不同位置或不同的组合可能出现不同的发音，学习者发音时须将减省的发音还原而并非直觉的一字对一音[注 12]，如“哥”和“给”中的e音素不同；j、q、x后的ü省去两点与介音“-u-”有两个音值而只用一个字母标不同；i有两个音值“即”和“至”，均用i标导致很多非官话语言区的中年人读不准;-ian、-üan（注意：-üan前接声母时省去两点，简写为-uan）中的a并不读/a/而是/ɛ/，不少非官话语言区的中年人会将“远”读成/jwan/，增加了学习者的困难。

哥，ju4 是 据 的正确拼法，如果需要匹配 jv4，可以考虑打开模糊音开关
