### ISSUE TITLE
游戏崩溃，显示jech和tconven冲突

### ISSUE THREAD

**Issue by Cayln-s** [Towdium/JustEnoughCharacters#39]
[错误报告 - 1.12.2-生存.zip](https://github.com/Towdium/JustEnoughCharacters/files/5964887/-.1.12.2-.zip)

**Comment by Cayln-s** [comment]
老手残党震怒，两个都喜欢的模组居然冲突了

**Comment by Towdium** [comment]
确定和 JECh 有关系吗？看日志感觉关系不大啊

**Comment by Cayln-s** [comment]
哦哦，是我搞错了……我看不懂崩溃报告，看到报告第一二行显示这两个模组就以为跟它们有关……后来才发现我还下载了一个Materialis的模组，这个模组是匠魂的附属，本来想无脑加模组好好玩匠魂的，结果才发现把这个模组禁用之后就没事了。大佬能不能指导一下这个模组描述里面崩溃解决方法具体是怎么操作的?“在模组前面加个1”我不太明白……mcmod评论区里面也有人说加了也没用……

**Comment by Towdium** [comment]
这个是因为 TiC 的两个附属有冲突，A 比 B 先加载就会崩溃，B 比 A 先加载就不会崩溃，这个没什么必然规律，取决于具体实现。模组文件名修改之后会影响到模组的加载顺序，有时候就能解决问题。没有必然解决冲突的方法，只能试试看，不行就去找作者改。
