### ISSUE TITLE
1.16.4版本无法使用拼音搜索tooltips内容

### ISSUE THREAD

**Issue by Death-123** [Towdium/JustEnoughCharacters#40]
![image](https://user-images.githubusercontent.com/50763371/109131150-81ff0500-778d-11eb-9534-b632763ad60b.png)![image](https://user-images.githubusercontent.com/50763371/109131176-86c3b900-778d-11eb-9e2d-26c27a2f5607.png)
![image](https://user-images.githubusercontent.com/50763371/109131265-95aa6b80-778d-11eb-9322-22a07a1c782e.png)

**Comment by Towdium** [comment]
收到，我康康

**Comment by Death-123** [comment]
emm,这个还不关吗,不是都修了吗(

**Comment by Towdium** [comment]
草 关了关了
这个你也可以自己关的其实
