### ISSUE TITLE
Fabric version?

### ISSUE THREAD

**Issue by plusls** [Towdium/JustEnoughCharacters#44]
请问我可以将这个 mod 移植到 fabric 上吗？

如果可以，需要加什么引用出处嘛

**Comment by Towdium** [comment]
当然可以！

目前这个项目是 MIT 授权，也就是说如果你使用了 JECh 的一部分源码，你需要声明来源。当然，目前的代码本身就很少，而且对于移植到 Fabric 而言几乎是没有帮助的，所以你大概也不会用到。你需要的大部分逻辑都在 [PinIn](https://github.com/Towdium/PinIn) 这个项目里，作为库来使用也是不需要声明来源的。PinIn 自身依赖的项目也没有这方面的要求。
