### ISSUE TITLE
JustEnoughCharacters-1.16.4-4.3.1.jar的Curseforge標籤為Fabric而不是Forge

### ISSUE THREAD

**Issue by Edel-Lilies** [Towdium/JustEnoughCharacters#46]
JustEnoughCharacters-1.16.4-4.3.1.jar的Curseforge標記為Fabric而不是Forge
https://www.curseforge.com/minecraft/mc-mods/just-enough-characters/files/3393831

**Comment by Towdium** [comment]
淦，我已经填错好几次了

**Comment by Towdium** [comment]
改回来了
