### ISSUE TITLE
等价交换的转化桌不支持拼音搜索

### ISSUE THREAD

**Issue by SheepYhangCN** [Towdium/JustEnoughCharacters#48]
之前用转化桌的搜索发现不支持拼音搜索
希望能支持一下这个Mod的搜索
实在不行单独发布个附属Mod也行（）

**Comment by Towdium** [comment]
发布链接给一个呗，等价交换分支太多，整不明白

**Comment by Towdium** [comment]
![2021-09-05_10 41 24](https://user-images.githubusercontent.com/10866568/132113102-11ce6caf-fea5-42b0-b860-624ace01dd1d.png)
我这边是好的啊
```
jecharacters-1.16.4-4.3.2.jar
ProjectE-1.16.5-PE1.0.1B.jar
```

**Comment by SheepYhangCN** [comment]
> ![2021-09-05_10 41 24](https://user-images.githubusercontent.com/10866568/132113102-11ce6caf-fea5-42b0-b860-624ace01dd1d.png)
> 我这边是好的啊
> 
> ```
> jecharacters-1.16.4-4.3.2.jar
> ProjectE-1.16.5-PE1.0.1B.jar
> ```

可能因为我用的是1.12.2版吧（

**Comment by Towdium** [comment]
```
ProjectE-1.12.2-PE1.4.1.jar
JustEnoughCharacters-1.12.0-3.5.1.jar
```
我寻思着这也没问题啊

**Comment by Towdium** [comment]
先关了，有问题再留言吧
