### ISSUE TITLE
Ticking screen Crash= =

### ISSUE THREAD

**Issue by Yesterday17** [Towdium/JustEnoughCharacters#5]
Description: Ticking screen
java.lang.ArrayIndexOutOfBoundsException: 67161

Crash Report:
https://gist.github.com/yesterday17/f0f6066938ca42dd4f24b1861eace0e0

具体操作是在Refined Storage里右键了一下清空文本的时候崩的。

涉及到的版本信息:
JustEnoughCharacters-1.11.2-1.6.3
refinedstorage-1.2.25

还有别的看Crash Report吧ww

**Comment by Towdium** [comment]
收到！似乎是我的缓存炸了

**Comment by Towdium** [comment]
修复大概还要一阵子...
不过现在用的话退回1.6（不含）之前的版本就可以了
功能是一样的

**Comment by Yesterday17** [comment]
没事 慢慢修吧 我那个档被RS炸了23333

**Comment by Towdium** [comment]
最新版大概已经修复了！

**Comment by Towdium** [comment]
目前先关闭了 如果有问题务必再告知我
