### ISSUE TITLE
1.16.5 启动时崩溃

### ISSUE THREAD

**Issue by endereyewxy** [Towdium/JustEnoughCharacters#50]
仅启用 Just Enough Items 和 Just Enough Characters 两个 MOD 的情况下，在启动时崩溃。

Java 17.0.1；
Forge 36.2.0，经测试最新版（36.2.9）也有相同问题；
Just Enough Items 7.7.1.137；
Just Enough Characters 1.16.4-4.3.2；

[debug.log](https://github.com/Towdium/JustEnoughCharacters/files/7574237/debug.log)
[latest.log](https://github.com/Towdium/JustEnoughCharacters/files/7574238/latest.log)

**Comment by Towdium** [comment]
这个跟我关系不大，可能是 forge coremod 不支持 java17，出问题的调用栈不是我的

**Comment by endereyewxy** [comment]
但是不加这个 MOD 就一点问题也没有

**Comment by Towdium** [comment]
目前 forge 的 coremod 不多，你的 mod 列表里可能没有其他 coremod，这里有几个连接可以参考：
https://forums.minecraftforge.net/topic/106083-help-can-forge-does-not-load-playing-minecraft-1165/
https://www.reddit.com/r/MinecraftServer/comments/pm7kw0/forge_mod_loader_crashes_on_startup/

**Comment by Profitter** [comment]
Java的问题，不要用Java17，用老版本的Java8就可以了
