### ISSUE TITLE
[1.12.2]不起效于Had Enough Items

### ISSUE THREAD

**Issue by ChromaPIE** [Towdium/JustEnoughCharacters#54]
https://www.curseforge.com/minecraft/mc-mods/had-enough-items

希望Just Enough Characters可以添加对这一JEI fork的支持。

**Comment by Towdium** [comment]
我看 Had Enough Items 好像主要也就是增加了一些内存优化什么的
但是说实话 JEI 的内存问题我之前就已经分析过了，只要安装 JECh 就可以将 JEI 的内存占用缩减到原来的 1/5 左右
而且传统方法对 JEI 的优化要么在 JECh 场景下不适用，要么就是会带来比较严重的性能问题
这个 mod 先观察观察吧，主要是 1.12 的不太想动了，搞起来有点麻烦

**Comment by vfyjxf** [comment]
@ChromaPIE 关于HEI的支持，CleanRoom整了个叫HadEnoughCharacters的分支，你可以关注一下，兼容我已经发pr了，应该在hei下版本发布时一起发布。

**Comment by vfyjxf** [comment]
Cleanroom发布了[HadEnoughCharacters](https://www.curseforge.com/minecraft/mc-mods/had-enough-characters),关于hei的兼容请使用hech.
