### ISSUE TITLE
希望升级到 1.18.2

### ISSUE THREAD

**Issue by HydrogenC** [Towdium/JustEnoughCharacters#55]
如题，jei已经有1.18.2的beta版了

**Comment by xuwuwudi** [comment]
jei搜索框无效（1.18.2）

**Comment by lbs3180** [comment]
希望升级到 1.18.2

**Comment by xuwuwudi** [comment]
呜呜qwq

**Comment by vfyjxf** [comment]
我已经提交了更新到1.18.2的pr了，只修复了jei兼容，急用的可以使用我的构建（jei版本:jei-1.18.2-9.5.5.174）
[mod.zip](https://github.com/Towdium/JustEnoughCharacters/files/8852570/mod.zip) （记得解压）

**Comment by vfyjxf** [comment]
> 我已经提交了更新到1.18.2的pr了，只修复了jei兼容，急用的可以使用我的构建（jei版本:jei-1.18.2-9.5.5.174） [mod.zip](https://github.com/Towdium/JustEnoughCharacters/files/8851920/mod.zip)

如果有其他mod失效的，也可以反馈给我，但我只能在少量的节假日时修复（）
