### ISSUE TITLE
1.18.1不起作用

### ISSUE THREAD

**Issue by jssda** [Towdium/JustEnoughCharacters#56]
# 环境
forge: 39.1.2
JEI: 1.18.1-9.4.1.172
JECH: 1.18.1-4.3.3

![image](https://user-images.githubusercontent.com/33473639/167260103-083f8a05-ab97-47df-90e7-22946764060d.png)
![image](https://user-images.githubusercontent.com/33473639/167260137-36438d40-c7c7-4c2d-971b-0da4d1a75008.png)

**Comment by jssda** [comment]
### 全量搜索报告
> 瞅了眼JEI相关的, emmm 看不懂 :)

[jecharacters.txt](https://github.com/Towdium/JustEnoughCharacters/files/8645462/jecharacters.txt)

**Comment by vfyjxf** [comment]
jei兼容已经在1.18.2时修复了，请更新mod。
