### ISSUE TITLE
AE2-RV4-alpha11 不支持 

### ISSUE THREAD

**Issue by wafer-li** [Towdium/JustEnoughCharacters#6]
minecraft: 1.10.2

forge: 12.18.3.2297

AE2-RV4-alpha11

插件版本: 1.9.1

问题表现：

AE2 终端中只能中文搜索、英文搜索和数字搜索；
JEI 中只能拼音搜索（不能英文搜索和数字搜索）

同时还装了植物魔法，植物魔法拼音搜索正常。

**Comment by Towdium** [comment]
收到！
根据以前的经验来看 ae 用的是正则表达式
这个要手动兼容
我现在就去看

**Comment by wafer-li** [comment]
后续发现：

AE2 接口终端与其他终端不一样，其行为类似 JEI。

植物魔法可以正常搜索中英文。

**Comment by Towdium** [comment]
Got!

**Comment by Towdium** [comment]
新版在 curseforge 发了，不过审核还要一阵子。如果还有问题请务必告知我。
我还有一个问题，看你这头像是二水笔？
不我觉得我应该认错人了（

**Comment by wafer-li** [comment]
我是最近才开始玩 MC 的，你肯定认错人了。

不过这个头像的确太多人用了，想换一个不过没找到好图 :pensive:

**Comment by Towdium** [comment]
噗= =
