### ISSUE TITLE
REI无法使用拼音搜索

### ISSUE THREAD

**Issue by Dr-WeiAL** [Towdium/JustEnoughCharacters#61]
版本是1.18.2 Forge
![image](https://user-images.githubusercontent.com/47446553/173275154-38af1bc8-66c0-492a-aa5b-413356bd83c5.png)
![image](https://user-images.githubusercontent.com/47446553/173275757-4777009d-399c-441e-81c5-e787a2e7148d.png)

**Comment by vfyjxf** [comment]
已经修复，请等待更新。
