### ISSUE TITLE
Mixin 加载错误导致原版搜索无法使用拼音

### ISSUE THREAD

**Issue by yezhiyi9670** [Towdium/JustEnoughCharacters#68]
游戏版本：1.19.2 Fabric

代码中有 Mixin 加载错误导致原版搜索不能正常使用拼音，修复后即恢复正常（已确认）。

[generate.gradle](https://github.com/Towdium/JustEnoughCharacters/blob/fabric-1.19/generate.gradle#L129) 中，`MixinVanillaPlainTextSearch` 应当为 `MixinVanillaTextSearch`。

**Comment by vfyjxf** [comment]
感谢反馈，我到时候看看能不能把现在这种引用字符串常量改成自动获取的形式，这样就不用人工匹配了。
