### ISSUE TITLE
与1.18.2的REI(Fabric)一起使用疑似失效？

### ISSUE THREAD

**Issue by Surgeol** [Towdium/JustEnoughCharacters#69]
REI版本为[Fabric 1.18.2] v8.3.556
JEC版本为1.18.2-fabric-4.3.9

我只启用了Mod Menu，REI，JEC这几个模组与相关前置
效果对比如下
_如果我是因为阅读理解不及格才导致不能用请告诉我 :(_

![example1](https://user-images.githubusercontent.com/35412032/197979885-c5913ebc-a7f6-4638-ad31-52419ad22321.png)
![example2](https://user-images.githubusercontent.com/35412032/197979894-e7379073-aeff-4e0e-82c6-0d23d7b1a2eb.png)

**Comment by vfyjxf** [comment]
其实也不算失效，因为我还没做rei的兼容，考虑到rei自带一个拼音搜索的功能，我可能需要考虑下如何给rei兼容.
