### ISSUE TITLE
1.19.2Fabric下的config配置文件无法修改，每次修改完成，启动游戏，jech参数恢复默认值

### ISSUE THREAD

**Issue by ZebraMartin** [Towdium/JustEnoughCharacters#74]
我就想改个小鹤双拼，用指令调只能生效本次游戏，再次启动游戏也是会还原的，所以还是希望可以正常修改配置文件

**Comment by ZebraMartin** [comment]
我就想改个小鹤双拼，用指令调只能生效本次游戏，再次启动游戏也是会还原的，所以还是希望可以正常修改配置文件

**Comment by vfyjxf** [comment]
应该是我不小心每次启动游戏的时候都重置配置文件了，等会看看怎么修(

**Comment by ZebraMartin** [comment]
好的，感谢感谢

**Comment by ZebraMartin** [comment]
可以修改配置文件了，可是双拼依旧无法生效

**Comment by vfyjxf** [comment]
好了，这次应该没问题了，等会传更新。

**Comment by ZebraMartin** [comment]
亲测，已经能够正常使用
