### ISSUE TITLE
1.9.3 导致 JEI 卡顿？

### ISSUE THREAD

**Issue by wafer-li** [Towdium/JustEnoughCharacters#8]
JEI 3.14.7.419

问题表现：

第一次一次性输入一整个词语会导致 JEI 卡顿，比如说 “书”，直接一次性输入 shu 会导致 JEI 卡顿。
第二次之后才能流畅的输入。

如果一个一个字母打则不会有这个情况。

前一个 1.9.1 版本不存在这个问题。

**Comment by Towdium** [comment]
是我把日志刷爆了...
刚刚应该修复了
不过 curseforge 还要审核

**Comment by wafer-li** [comment]
…… 不如先发一个 github release 吧？我这边的确卡的不行……

实际上只要配置一下 gradle 插件即可自动化 release。
