### ISSUE TITLE
[向下兼容]可以兼容1.17.1吗？RECh我也看了，也不支持1.17.1😭

### ISSUE THREAD

**Issue by BovinLiu** [Towdium/JustEnoughCharacters#86]

**Comment by vfyjxf** [comment]
这个版本真的是不上不下，感觉没啥人玩(
你要不试试能不能跑1.16或者1.18的mod

**Comment by BovinLiu** [comment]
好，我去试试，还是十分感谢大佬对这个mod的辛勤付出awa
（实在不行的话我就常切换输入法或者多背点游戏里常用物品的英文单词，到时候直接搜英文也一样～）

**Comment by BovinLiu** [comment]
很遗憾，这两个版本的mod我都试了，都不行😭

**Comment by vfyjxf** [comment]
等我这几天能不能重构完jech把，重构后的jech会提供对非主流版本的最基本的支持（加了jech游戏不会崩溃那种）

**Comment by vfyjxf** [comment]
目前无计划支持1.17
