### ISSUE TITLE
Not support jei version jei-1.16.5-7.8.0.1009

### ISSUE THREAD

**Issue by suoliangao** [Towdium/JustEnoughCharacters#88]
整合包：E6E-1.7.1 | E6E-1.8.0
Forge版本：1.16.5-36.2.39
jei版本：1.16.5-7.8.0.1009
问题：拼音搜索不生效
测试替换为旧版本jei可以解决问题
更多细节没有测试

**Comment by vfyjxf** [comment]
这个问题其实我早知道了，原因是jei把1.16之后做的性能优化移植到了1.16的版本上，导致jech兼容性失效，我这几天抽空修。

**Comment by vfyjxf** [comment]
已修复，请更新最新版本jech。

**Comment by ChenMoFeiJin** [comment]
Minecraft: 1.16.5
Forge: 1.16.5-36.2.39
JEI: 1.16.5-7.8.0.1009
JEC: 1.16.4-4.3.9
@vfyjxf 问题好像没有被修复，最新的 4.3.9 在 JEI 7.8.0.109 和 7.7.1.153 上都是无效的，但是 4.3.8 版本在 JEI 7.7.1.153 上是有效的
![image](https://github.com/Towdium/JustEnoughCharacters/assets/42508525/2cb2d484-5752-4a69-9491-587e95412fea)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/42508525/9609858f-8a9d-47d8-9756-b74e20c9ca0e)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/42508525/0aae6ea4-970c-4294-9609-44ee50993105)
