### ISSUE TITLE
在nomifactory（GTCEu）无法使用

### ISSUE THREAD

**Issue by threestarsQAQ** [Towdium/JustEnoughCharacters#89]
![image](https://github.com/Towdium/JustEnoughCharacters/assets/106313729/e884146d-4c3f-49f2-9c6c-26700af4cb03)

![image](https://github.com/Towdium/JustEnoughCharacters/assets/106313729/2a39c49f-00f1-415b-ac8d-8faea28cc2e0)

**Comment by vfyjxf** [comment]
hei请使用[hech](https://legacy.curseforge.com/minecraft/mc-mods/had-enough-characters)
