### ISSUE TITLE
不支持英文搜索

### ISSUE THREAD

**Issue by wafer-li** [Towdium/JustEnoughCharacters#9]
装了之后 JEI 不能搜索英文了，AE2 的接口终端同理。

比如说输入 “MFSU” 就搜索不到了。

目前装了 943 的那个中文资源包，不知道会不会有影响。

**Comment by Towdium** [comment]
收到！
我去看看

确实有这个问题 大概是新的算法写漏了

**Comment by Towdium** [comment]
How is it?

[JustEnoughCharacters-1.12-1.9.5.zip](https://github.com/Towdium/JustEnoughCharacters/files/1184893/JustEnoughCharacters-1.12-1.9.5.zip)

**Comment by wafer-li** [comment]
Fixed.
