### ISSUE TITLE
JEI version jei-1.16.5-7.8.0.1009 is still not supported

### ISSUE THREAD

**Issue by ChenMoFeiJin** [Towdium/JustEnoughCharacters#92]
Minecraft: 1.16.5
Forge: 1.16.5-36.2.39
JEI: 1.16.5-7.8.0.1009
JEC: 1.16.4-4.3.9
@vfyjxf 问题好像没有被修复，最新的 4.3.9 在 JEI 7.8.0.109 和 7.7.1.153 上都是无效的，但是 4.3.8 版本在 JEI 7.7.1.153 上是有效的
![image](https://github.com/Towdium/JustEnoughCharacters/assets/42508525/2cb2d484-5752-4a69-9491-587e95412fea)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/42508525/9609858f-8a9d-47d8-9756-b74e20c9ca0e)
![image](https://github.com/Towdium/JustEnoughCharacters/assets/42508525/0aae6ea4-970c-4294-9609-44ee50993105)

_Originally posted by @ChenMoFeiJin in https://github.com/Towdium/JustEnoughCharacters/issues/88#issuecomment-1635634632_

**Comment by vfyjxf** [comment]
由[Death-123](https://github.com/Death-123)在[#90](https://github.com/Towdium/JustEnoughCharacters/pull/90)修复
